"use client"

import type React from "react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Download, Plus, Share2, FileText, Trash2 } from "lucide-react"
import { useHealthData } from "@/hooks/use-health-data"

export default function ReportsPage() {
  const { data, addReport, deleteReport } = useHealthData()
  const [showUploadDialog, setShowUploadDialog] = useState(false)
  const [formData, setFormData] = useState({
    name: "",
    type: "Lab Results",
    date: "",
  })

  if (!data) {
    return (
      <main className="min-h-screen bg-background py-8">
        <div className="mx-auto max-w-6xl px-6">
          <p className="text-muted-foreground">Loading reports...</p>
        </div>
      </main>
    )
  }

  const handleUpload = (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.name || !formData.date) {
      alert("Please fill in all fields")
      return
    }

    addReport({
      id: `report_${Date.now()}`,
      name: formData.name,
      date: formData.date,
      type: formData.type,
      uploadedAt: new Date().toISOString(),
    })

    setFormData({
      name: "",
      type: "Lab Results",
      date: "",
    })
    setShowUploadDialog(false)
    alert("Report uploaded successfully!")
  }

  const handleDownloadReport = (reportId: string, reportName: string) => {
    const report = data.reports.find((r) => r.id === reportId)
    if (!report) return

    const reportContent = `
HEALTH REPORT
=============
Name: ${reportName}
Type: ${report.type}
Date: ${report.date}
Uploaded: ${report.uploadedAt}

Patient: ${data.user.fullName}
Contact: ${data.user.phone}

---
Report generated by QuraAI Health Management System
For more information, visit your dashboard.
    `.trim()

    const element = document.createElement("a")
    const file = new Blob([reportContent], { type: "text/plain;charset=utf-8" })
    element.href = URL.createObjectURL(file)
    element.download = `${reportName}-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleShareReport = (reportName: string) => {
    const report = data.reports.find((r) => r.name === reportName)
    if (!report) return

    const reportContent = `
HEALTH REPORT - ${reportName}
Generated: ${new Date().toLocaleDateString()}

Patient Information:
${data.user.fullName} | ${data.user.phone} | ${data.user.email}

Current Medications:
${data.medicines
  .filter((m) => m.status === "active")
  .map((m) => `- ${m.name} ${m.dosage}`)
  .join("\n")}

Allergies: ${data.user.allergies.length > 0 ? data.user.allergies.join(", ") : "None"}
Conditions: ${data.user.chronicConditions.length > 0 ? data.user.chronicConditions.join(", ") : "None"}

---
This report was generated by QuraAI.
Please consult your healthcare provider for medical advice.
    `.trim()

    const email = `mailto:doctor@example.com?subject=Patient Report - ${reportName}&body=${encodeURIComponent(reportContent)}`
    window.location.href = email
  }

  const reportTypes = ["Lab Results", "General Checkup", "Prescription", "Imaging", "Other"]

  return (
    <main className="min-h-screen bg-background py-8">
      <div className="mx-auto max-w-6xl px-6">
        {/* Header */}
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground">Health Reports</h1>
            <p className="mt-2 text-muted-foreground">Manage your medical documents and health reports</p>
          </div>
          <Dialog open={showUploadDialog} onOpenChange={setShowUploadDialog}>
            <DialogTrigger asChild>
              <Button className="bg-primary hover:bg-primary/90">
                <Plus className="mr-2 h-4 w-4" />
                Upload Report
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-md">
              <DialogHeader>
                <DialogTitle>Upload New Report</DialogTitle>
                <DialogDescription>Add a new health report or document</DialogDescription>
              </DialogHeader>
              <form onSubmit={handleUpload} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="reportName">Report Name</Label>
                  <Input
                    id="reportName"
                    placeholder="e.g., Blood Test Results"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="reportType">Report Type</Label>
                  <select
                    id="reportType"
                    value={formData.type}
                    onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                    className="w-full rounded-md border border-input bg-background px-3 py-2"
                  >
                    {reportTypes.map((type) => (
                      <option key={type} value={type}>
                        {type}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="reportDate">Date</Label>
                  <Input
                    id="reportDate"
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  />
                </div>

                <Button type="submit" className="w-full bg-primary hover:bg-primary/90">
                  Upload Report
                </Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        {/* Reports List */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {data.reports.length === 0 ? (
            <Card className="md:col-span-2 lg:col-span-3">
              <CardContent className="flex h-64 items-center justify-center text-center">
                <div>
                  <FileText className="mx-auto mb-4 h-12 w-12 text-muted-foreground" />
                  <p className="text-lg font-semibold text-foreground">No reports yet</p>
                  <p className="text-sm text-muted-foreground">Upload your first health report to get started</p>
                </div>
              </CardContent>
            </Card>
          ) : (
            data.reports.map((report) => (
              <Card key={report.id} className="flex flex-col">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div>
                      <CardTitle className="text-lg">{report.name}</CardTitle>
                      <CardDescription>{report.type}</CardDescription>
                    </div>
                    <FileText className="h-5 w-5 text-primary" />
                  </div>
                </CardHeader>
                <CardContent className="flex-1 space-y-4">
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground">DATE</p>
                    <p className="text-sm text-foreground">{report.date}</p>
                  </div>
                  {report.aiAnalysis && (
                    <div className="rounded-lg bg-primary/5 p-3">
                      <p className="text-xs font-semibold text-muted-foreground mb-1">AI Analysis</p>
                      <p className="text-xs text-muted-foreground">{report.aiAnalysis}</p>
                    </div>
                  )}
                </CardContent>
                <div className="border-t border-border p-4 flex gap-2">
                  <Button
                    size="sm"
                    className="flex-1 bg-primary hover:bg-primary/90"
                    onClick={() => handleDownloadReport(report.id, report.name)}
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="flex-1 bg-transparent"
                    onClick={() => handleShareReport(report.name)}
                  >
                    <Share2 className="mr-2 h-4 w-4" />
                    Share
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="bg-transparent"
                    onClick={() => {
                      if (confirm("Are you sure you want to delete this report?")) {
                        deleteReport(report.id)
                      }
                    }}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </Card>
            ))
          )}
        </div>
      </div>
    </main>
  )
}
